# -*- coding: utf-8 -*-
"""
build_phenomena.py
------------------
Reads  json/results.csv  (FILENAME, PHENOMENON)
Looks up the slug field in each matching JSON file
Writes sermon-phenomena.csv  (SLUG, FILENAME, PHENOMENON)  in the repo root
Writes phenomena_data.js     (const PHENOMENA = { slug: [...], ... })
"""

import csv
import json
import os

JSON_DIR   = 'json'
INPUT_CSV  = os.path.join(JSON_DIR, 'results.csv')
OUTPUT_CSV = 'sermon-phenomena.csv'
OUTPUT_JS  = 'phenomena_data.js'

# ── 1. Build filename → slug map from all JSON files ──────────────────────────
filename_to_slug = {}
for fname in os.listdir(JSON_DIR):
    if not fname.endswith('.json'):
        continue
    path = os.path.join(JSON_DIR, fname)
    try:
        with open(path, encoding='utf-8') as fh:
            data = json.load(fh)
        slug = data.get('slug', '').strip()
        if slug:
            filename_to_slug[fname] = slug
    except Exception as exc:
        print(f'  [warn] could not read {fname}: {exc}')

print(f'Loaded slugs for {len(filename_to_slug)} JSON files')

# ── 2. Read results.csv and enrich with slug ───────────────────────────────────
rows = []
missing = set()
with open(INPUT_CSV, encoding='utf-8', newline='') as fh:
    for row in csv.DictReader(fh):
        fname    = row['FILENAME'].strip()
        slug     = filename_to_slug.get(fname, '')
        if not slug:
            missing.add(fname)
        rows.append({'SLUG': slug, 'FILENAME': fname, 'PHENOMENON': row['PHENOMENON'].strip()})

if missing:
    print(f'  [warn] no slug found for: {", ".join(sorted(missing))}')

# ── 3. Write sermon-phenomena.csv ─────────────────────────────────────────────
with open(OUTPUT_CSV, 'w', encoding='utf-8', newline='') as fh:
    writer = csv.DictWriter(fh, fieldnames=['SLUG', 'FILENAME', 'PHENOMENON'])
    writer.writeheader()
    writer.writerows(rows)
print(f'Written {len(rows)} rows -> {OUTPUT_CSV}')

# ── 4. Build slug → [phenomena] map ───────────────────────────────────────────
phenomena_map = {}
for row in rows:
    slug = row['SLUG']
    if slug:
        phenomena_map.setdefault(slug, []).append(row['PHENOMENON'])

# ── 5. Write phenomena_data.js ────────────────────────────────────────────────
with open(OUTPUT_JS, 'w', encoding='utf-8') as fh:
    fh.write('// Auto-generated by build_phenomena.py — do not edit manually\n')
    fh.write('const PHENOMENA = ')
    json.dump(phenomena_map, fh, ensure_ascii=False, indent=2)
    fh.write(';\n')
print(f'Written phenomena_data.js  ({len(phenomena_map)} entries)')
