// Auto-generated by build_phenomena.py — do not edit manually
const PHENOMENA = {
  "1556-roerer-ein-predig-von": [
    "Wetter",
    "Witterung/Gewitter",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Dürre",
    "Hagel",
    "Flut"
  ],
  "1565-alber-eine-summa-etlicher": [
    "Witterung/Gewitter",
    "Finsternuß/Finsternis",
    "Schnee",
    "Dürre",
    "Hagel"
  ],
  "1566-rorer-eine-predigt-von": [
    "Wetter",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Hagel",
    "Sommer"
  ],
  "1571-lavater-von-thuewre-vn": [
    "Witterung/Gewitter",
    "Wind",
    "Winter",
    "Frost",
    "Schnee",
    "Dürre",
    "Hagel"
  ],
  "1589-alber-eine-summa-etlicher": [
    "Finsternuß/Finsternis",
    "Regen/Blutregen/Regenbogen",
    "Schnee",
    "Hagel"
  ],
  "1599-fabricius-christliche-predigt-von": [
    "Wind",
    "Regen/Blutregen/Regenbogen",
    "Nebel",
    "Kälte",
    "Schnee"
  ],
  "1613-schilling-vier-predigten-von": [
    "Wetter",
    "Wind",
    "Finsternuß/Finsternis",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Komet/Comet",
    "Frost",
    "Schnee",
    "Dürre",
    "Hagel",
    "Hitze",
    "Flut",
    "Frühling/Frühjahr/Lenz"
  ],
  "1616-titius-eine-christliche-und": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Kälte",
    "Dürre",
    "Hagel",
    "Hitze",
    "Feuchte",
    "Sommer"
  ],
  "1658-tappe-der-mensch-weiss": [
    "Wetter",
    "Regen/Blutregen/Regenbogen"
  ],
  "1664-heland-est-visa-dei": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Eis",
    "Hagel",
    "Sturm",
    "Dampf",
    "Sommer"
  ],
  "1666-wessel-des-himmel-koenigs-wetter-geschuetze": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Kälte",
    "Schnee",
    "Hagel",
    "Hitze",
    "Sturm",
    "Dampf",
    "Sommer"
  ],
  "1706-cuno-den-schnee-als": [
    "Wetter",
    "Schnee"
  ],
  "1720-pregitzer-das-von-gott": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Finsternuß/Finsternis",
    "Regen/Blutregen/Regenbogen",
    "Frost",
    "Kälte",
    "Schnee",
    "Dürre",
    "Hagel",
    "Hitze",
    "Sturm",
    "Flut",
    "Herbst"
  ],
  "1720-tafinger-der-ausbruch-goettlicher": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Finsternuß/Finsternis",
    "Regen/Blutregen/Regenbogen",
    "Frost",
    "Dürre",
    "Hagel",
    "Hitze",
    "Herbst"
  ],
  "1637-schilling-drey-christliche-thewrung": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Regen/Blutregen/Regenbogen",
    "Komet/Comet",
    "Frost",
    "Kälte",
    "Dürre",
    "Hagel",
    "Flut",
    "Sommer"
  ],
  "1639-reinhold-bronteiologike-gehalten-durch": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Finsternuß/Finsternis",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Schnee",
    "Hagel",
    "Sturm",
    "Flut"
  ],
  "1649-alard-hiobitische-truebsaell-als": [
    "Wetter",
    "Witterung/Gewitter",
    "Finsternuß/Finsternis",
    "Regen/Blutregen/Regenbogen",
    "Komet/Comet",
    "Kälte",
    "Schnee",
    "Eis",
    "Dürre",
    "Hagel",
    "Hitze",
    "Sturm",
    "Sommer"
  ],
  "1705-andreae-gottes-herrliche-heilige": [
    "Wetter",
    "Witterung/Gewitter",
    "Regen/Blutregen/Regenbogen",
    "Nebel",
    "Schnee",
    "Hagel",
    "Hitze",
    "Sturm"
  ],
  "1705-graefe-gottes-majestaet-und": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Frost",
    "Kälte",
    "Schnee",
    "Dürre",
    "Hagel",
    "Hitze",
    "Sommer",
    "Herbst"
  ],
  "1707-stolle-el-lemoshaot-der": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Winter",
    "Regen/Blutregen/Regenbogen",
    "Kälte",
    "Schnee",
    "Hagel",
    "Hitze",
    "Sommer"
  ],
  "1748-knebel-wie-gott-denen": [
    "Wetter",
    "Witterung/Gewitter",
    "Wind",
    "Hagel",
    "Sturm"
  ]
};
