# -*- coding: utf-8 -*-
"""
build_phenomena.py
------------------
STAGE 2 of the data pipeline (phenomena branch).
Reads   json/*.json          (slug + text fields)
Writes  metadata/sermon-weather-phenomena.csv  (SERMON_SLUG, JSON_FILE, WEATHER_PHENOMENON)
Writes  phenomena_data.js                      (const PHENOMENA = {slug: [...], ...})

No intermediate results.csv required — extraction is done inline.

Run from repo root:  python scripts/build_phenomena.py
"""

import csv
import json
import os
import re

JSON_DIR   = 'json'
OUTPUT_CSV = 'metadata/sermon-weather-phenomena.csv'
OUTPUT_JS  = 'phenomena_data.js'

# ─────────────────────────────────────────────────────────────────────────────
# Weather / phenomenon term dictionary
# Each key is the canonical label; value is a list of spelling variants.
# Search is case-insensitive, whole-word (word boundaries).
# ─────────────────────────────────────────────────────────────────────────────
WEATHER_TERMS = {
    "Wetter":                      ["Wetter"],
    "Witterung/Gewitter":          ["Witterung", "Gewitter", "Witter"],
    "Meteor/Meteorologie":         ["Meteor", "Meteorologie"],
    "Wind":                        ["Wind"],
    "Finsternuß/Finsternis":       ["Finsternuß", "Finsternis"],
    "Winter":                      ["Winter", "Wintr"],
    "Regen/Blutregen/Regenbogen":  ["Regen", "Blutregen", "Regenbogen", "Regn"],
    "Nebel":                       ["Nebel"],
    "Komet/Comet":                 ["Komet", "Comet"],
    "Frost":                       ["Frost"],
    "Kälte":                       ["Kaelt", "Kält", "Kaelte", "Kälte"],
    "Schnee":                      ["Schnee"],
    "Eis":                         ["Eis"],
    "Dürre":                       ["Dürre", "Durre"],
    "Trockenheit":                 ["Trock", "Trocknung", "Trockenheit"],
    "Hagel":                       ["Hagel"],
    "Hitze":                       ["Hitze"],
    "Sturm":                       ["Sturm"],
    "Feuchte":                     ["Feuchte"],
    "Niederschlag":                ["Niederschlag"],
    "Dampf":                       ["Dampf"],
    "Exhalationes":                ["Exhalationes"],
    "Dunkst":                      ["Dunkst"],
    "Vapor":                       ["Vapor"],
    "Flut":                        ["Flut"],
    "Sommer":                      ["Sommer"],
    "Herbst":                      ["Herbst"],
    "Frühling/Frühjahr/Lenz":      ["Frühling", "Fruehling", "Frühjahr", "Fruehjahr", "Lenz"],
    "kalt":                        ["kalt"],
    "heiß":                        ["heiß", "heiss"],
    "Schlossen/Schloßen":          ["Schlossen", "Schloßen"],
    "Wasser":                      ["Wasser"],
    "Sonne":                       ["Sonne"],
    "Verdunkelung/Dunkelheit":     ["Verdunkelung", "Dunkelheit"],
    "Wolke":                       ["Wolke"],
}

# Pre-compile one regex per canonical term
COMPILED_TERMS = {
    label: re.compile(
        r'\b(' + '|'.join(re.escape(v) for v in variants) + r')\b',
        re.IGNORECASE
    )
    for label, variants in WEATHER_TERMS.items()
}


def find_phenomena(text: str) -> list:
    """Return sorted list of canonical labels found in text."""
    return [label for label, pat in COMPILED_TERMS.items() if pat.search(text)]


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
rows          = []
phenomena_map = {}   # slug → [phenomena list]

json_files = sorted(f for f in os.listdir(JSON_DIR) if f.endswith('.json'))

for fname in json_files:
    path = os.path.join(JSON_DIR, fname)
    try:
        data = json.loads(open(path, encoding='utf-8').read())
    except Exception as exc:
        print(f'  [warn] could not read {fname}: {exc}')
        continue

    slug = data.get('slug', '').strip()
    text = data.get('text', '')

    if not slug:
        print(f'  [warn] no slug in {fname}')
        continue
    if not text:
        continue

    phenomena = find_phenomena(text)
    print(f'{fname}: {len(phenomena)} phenomenon/a')

    for ph in phenomena:
        rows.append({'SERMON_SLUG': slug, 'JSON_FILE': fname, 'WEATHER_PHENOMENON': ph})
    if phenomena:
        phenomena_map[slug] = phenomena

# ── Write sermon-weather-phenomena.csv ────────────────────────────────────────
os.makedirs('metadata', exist_ok=True)
with open(OUTPUT_CSV, 'w', encoding='utf-8', newline='') as fh:
    writer = csv.DictWriter(fh, fieldnames=['SERMON_SLUG', 'JSON_FILE', 'WEATHER_PHENOMENON'])
    writer.writeheader()
    writer.writerows(rows)
print(f'\nWritten {len(rows)} rows -> {OUTPUT_CSV}')

# ── Write phenomena_data.js ───────────────────────────────────────────────────
with open(OUTPUT_JS, 'w', encoding='utf-8') as fh:
    fh.write('// Auto-generated by build_phenomena.py — do not edit manually\n')
    fh.write('const PHENOMENA = ')
    json.dump(phenomena_map, fh, ensure_ascii=False, indent=2)
    fh.write(';\n')
print(f'Written phenomena_data.js  ({len(phenomena_map)} entries)')
