# -*- coding: utf-8 -*-
"""
build_weather_data.py
---------------------
Reads  metadata/weather-events.csv  (QUERY_CITY, DATE, LOCATION, EVENT_TYPE)
Writes weather_data.js              (const WEATHER = [...])

The 'year' field is a decimal year computed from DATE
(YYYY, YYYY-MM, YYYY-MM-DD, or YYYY-MM-DD HH:MM all supported).
"""

import csv
import json
import re

INPUT_CSV = 'metadata/weather-events.csv'
OUTPUT_JS = 'weather_data.js'


def parse_year(date):
    """Convert a DATE string to a decimal year (float)."""
    if not date:
        return None
    m = re.match(r'(\d{4})(?:-(\d{1,2})(?:-(\d{1,2}))?)?', date.strip())
    if not m:
        return None
    y  = int(m.group(1))
    mo = int(m.group(2)) if m.group(2) else 1
    dy = int(m.group(3)) if m.group(3) else 1
    return round(y + (mo - 1) / 12 + (dy - 1) / 365, 4)


rows = []
with open(INPUT_CSV, encoding='utf-8', newline='') as fh:
    for row in csv.DictReader(fh):
        city    = row['QUERY_CITY'].strip()
        period  = row['DATE'].strip()
        pos     = row['LOCATION'].strip()
        coding  = row['EVENT_TYPE'].strip()
        year    = parse_year(period)
        rows.append({
            'city':      city,
            'period':    period,
            'position':  pos,
            'coding':    coding,
            'year':      year,
        })

with open(OUTPUT_JS, 'w', encoding='utf-8') as fh:
    fh.write('// Auto-generated by build_weather_data.py — do not edit manually\n')
    fh.write('const WEATHER = ')
    json.dump(rows, fh, ensure_ascii=False, indent=2)
    fh.write(';\n')

print(f'Written {len(rows)} entries -> {OUTPUT_JS}')
cities = sorted(set(r['city'] for r in rows))
print(f'Cities ({len(cities)}): {", ".join(cities)}')
